# Generated by Django 4.1.4 on 2024-02-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhandle', '0002_doctors_contact'),
        ('medicaltrust', '0004_dlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='myac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhandle.doctors')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaltrust.registration')),
            ],
        ),
    ]
