# Generated by Django 4.1.4 on 2024-02-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaltrust', '0006_alter_myac_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myac',
            name='status',
        ),
        migrations.AddField(
            model_name='myac',
            name='message',
            field=models.TextField(default=0),
        ),
    ]
