# Generated by Django 4.1.4 on 2024-02-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('doctors_name', models.CharField(max_length=60)),
                ('doctor_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
