# Generated by Django 4.1.4 on 2024-02-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhandle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='contact',
            field=models.IntegerField(default=1),
        ),
    ]
