# Generated by Django 4.1.4 on 2024-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhandle', '0002_doctors_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experiance',
            field=models.IntegerField(default=2),
        ),
    ]
